# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import keyvaluestore_pb2 as keyvaluestore__pb2


class KeyValueStoreStub(object):
    """A simple key-value storage service
    This is main API of interacting with the chord network
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetValues = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/GetValues',
                request_serializer=keyvaluestore__pb2.GetRequest.SerializeToString,
                response_deserializer=keyvaluestore__pb2.GetResponse.FromString,
                )
        self.SetValue = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/SetValue',
                request_serializer=keyvaluestore__pb2.SetRequest.SerializeToString,
                response_deserializer=keyvaluestore__pb2.SetResponse.FromString,
                )


class KeyValueStoreServicer(object):
    """A simple key-value storage service
    This is main API of interacting with the chord network
    """

    def GetValues(self, request, context):
        """Provides a value for each key request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetValue(self, request, context):
        """Sets a value on the given key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValues,
                    request_deserializer=keyvaluestore__pb2.GetRequest.FromString,
                    response_serializer=keyvaluestore__pb2.GetResponse.SerializeToString,
            ),
            'SetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetValue,
                    request_deserializer=keyvaluestore__pb2.SetRequest.FromString,
                    response_serializer=keyvaluestore__pb2.SetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keyvaluestore.KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """A simple key-value storage service
    This is main API of interacting with the chord network
    """

    @staticmethod
    def GetValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/GetValues',
            keyvaluestore__pb2.GetRequest.SerializeToString,
            keyvaluestore__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/SetValue',
            keyvaluestore__pb2.SetRequest.SerializeToString,
            keyvaluestore__pb2.SetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
